[platformio]
src_dir = main

[env:esp32-s3-devkitm-1]
platform      = espressif32
board         = esp32-s3-devkitm-1
framework     = espidf
monitor_speed = 115200
upload_speed  = 921600

monitor_dtr = 1
monitor_rts = 1